from pathlib import Path
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
R=Path(__file__).resolve().parents[1];out=R/'supplementary_information/Source_Figure_Crosswalk.pdf'
styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='SmallBody',fontName='Times-Roman',fontSize=10,leading=13,spaceAfter=7));styles.add(ParagraphStyle(name='Cell',fontName='Times-Roman',fontSize=9,leading=11));styles.add(ParagraphStyle(name='HeadCell',fontName='Times-Bold',fontSize=9,leading=11))
story=[Paragraph('Figure and source-table correspondence',styles['Heading2']),Paragraph('Analysis source identifiers and filenames in Additional file 3 preserve the provenance of the numerical data. The following crosswalk identifies their final manuscript locations. Source filenames are identifiers, rather than final figure citations. The complete 89-row worksheet-cell map is provided in Additional file 9.',styles['SmallBody'])]
rows=[['Analysis source scope','Final figure and panel scope'],['Figure 1, A–J','Main Figure 1, B–K'],['Figure 2, A–J','Main Figure 2, A–J'],['Figure 3, A–J','Main Figure 3, A–J'],['Figure 4, A–J (liver localization and calibration)','Supplementary Figure S12, B–K'],['Figure 5, A–L (integration)','Main Figure 5, B–M'],['Figure 6, A–L (independent hepatic evaluation)','Main Figure 6, B–M'],['Supplementary Figures S1–S10','Supplementary Figures S1–S10'],['PXD052594 phosphoproteome sensitivity','Table-only results in Additional file 3']]
data=[[Paragraph(c,styles['HeadCell' if i==0 else 'Cell']) for c in row] for i,row in enumerate(rows)]
t=Table(data,colWidths=[235,245],hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#E7EDF2')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),('LINEBELOW',(0,0),(-1,0),.7,colors.black),('LINEBELOW',(0,-1),(-1,-1),.5,colors.black)]));story+=[t,Spacer(1,10),Paragraph('Panel A of Main Figures 1, 5 and 6 and Figure S12 presents the relevant workflow. The biochemical Main Figure 4 is supported by Additional files 4–6. It is distinct from the source-localization figure identified as Figure 4 in the source workbook.',styles['SmallBody']),Paragraph('Compound-screening sources',styles['Heading3'])]
rows=[['Supplementary table','Content and figure use'],['N20','Compound library and clinical context (Figure 7)'],['N21','All 32 AI-screening dispositions (Figure 7B,C)'],['N22–N23','96 primary searches and 32 summaries (Figure S13A–D)'],['N24','48 molecular-property predictions (Figure S14A–C)'],['N25–N26','Activity disposition and endpoint summaries (Figure S13E)'],['N27','Source-matched dissociation constants (Figure 7A)']]
t=Table([[Paragraph(c,styles['HeadCell' if i==0 else 'Cell']) for c in row] for i,row in enumerate(rows)],colWidths=[115,365],hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#E7EDF2')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4),('LINEBELOW',(0,0),(-1,0),.7,colors.black),('LINEBELOW',(0,-1),(-1,-1),.5,colors.black)]));story+=[t,Spacer(1,10),Paragraph('Additional file 9 contains the Figure S13F pose-level distances, the six primary/apo PDGFRA top-pose comparisons in Figure S14F, all 53 retained PDGFRA sensitivity poses, receptor definitions and exact model inputs. The three apo searches are separate from the 96 primary searches in Table N22. Current legends for S11–S12 are in Additional file 4; those for S13–S14 are in Additional file 7.',styles['SmallBody'])]
def footer(c,d):c.setFont('Times-Roman',10);c.drawCentredString(A4[0]/2,30,'93')
SimpleDocTemplate(str(out),pagesize=A4,leftMargin=57,rightMargin=57,topMargin=45,bottomMargin=45).build(story,onFirstPage=footer)
print(out)
